CREATE DATABASE IF NOT EXISTS btcdb;

USE btcdb;

CREATE TABLE IF NOT EXISTS public_addresses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    private_key VARCHAR(255) NOT NULL,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE USER IF NOT EXISTS 'btcuser'@'%' IDENTIFIED BY 'btcpass';

GRANT ALL PRIVILEGES ON btcdb.* TO 'btcuser'@'%';

FLUSH PRIVILEGES;
