apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: keygen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/bitcoin-keys-generator/keygen-repo/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: btcuser
        - name: DB_PASS
          value: btcpass
        - name: DB_NAME
          value: btcdb
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: keygen
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
