# MySQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: keygen
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
        - name: MYSQL_DATABASE
          value: btcdb
        - name: MYSQL_USER
          value: btcuser
        - name: MYSQL_PASSWORD
          value: btcpass
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: keygen
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
  type: ClusterIP

# Backend (also serves UI)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: keygen
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/bitcoin-keys-generator/keygen-repo/backend:latest
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: btcuser
        - name: DB_PASS
          value: btcpass
        - name: DB_NAME
          value: btcdb
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: keygen
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 8000
