apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: keygen
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend   # must match backend Deployment name
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50   # target 50% CPU
