apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: keygen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
        - name: MYSQL_DATABASE
          value: btcdb
        - name: MYSQL_USER
          value: btcuser
        - name: MYSQL_PASSWORD
          value: btcpass
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: keygen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---      
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: keygen
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
